# Generated by Django 3.1.5 on 2021-02-02 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_auto_20210202_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='emp_nu',
        ),
        migrations.AddField(
            model_name='branch',
            name='emp_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.employee'),
        ),
    ]
